/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSourceDialog: typeof import('./components/dialogs/AddSourceDialog.vue')['default']
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Cassette: typeof import('./components/cassette/Cassette.vue')['default']
    CassetteActionsBar: typeof import('./components/CassetteActionsBar.vue')['default']
    CassetteInfoDrawer: typeof import('./components/CassetteInfoDrawer.vue')['default']
    CassetteItem: typeof import('./components/cassette/CassetteItem.vue')['default']
    CassetteSide: typeof import('./components/cassette/CassetteSide.vue')['default']
    PlaylistList: typeof import('./components/PlaylistList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAlbumsTab: typeof import('./components/SearchAlbumsTab.vue')['default']
    SearchPlaylistsTab: typeof import('./components/SearchPlaylistsTab.vue')['default']
    UnavailableCassetteItem: typeof import('./components/UnavailableCassetteItem.vue')['default']
    UnavailableTracksList: typeof import('./components/UnavailableTracksList.vue')['default']
    UploadCassetteDialog: typeof import('./components/dialogs/UploadCassetteDialog.vue')['default']
    UserPlaylistsTab: typeof import('./components/UserPlaylistsTab.vue')['default']
  }
}
