/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cassette: typeof import('./components/Cassette.vue')['default']
    CassetteSide: typeof import('./components/CassetteSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackItem: typeof import('./components/TrackItem.vue')['default']
  }
}
