/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    Cassette: typeof import('./components/Cassette.vue')['default']
    CassetteSide: typeof import('./components/CassetteSide.vue')['default']
    ListLoader: typeof import('./components/ListLoader.vue')['default']
    PlaylistList: typeof import('./components/PlaylistList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackItem: typeof import('./components/TrackItem.vue')['default']
  }
}
